name: Publish LazyCat application

on:
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch:

jobs:
  lazycat:
    uses: wcaqrl/lazycat-action/.github/workflows/lazycat.yml@v1
    with:
      config: lazycat-action.yml
      operation: auto
      toolchains: docker
    secrets: inherit
